###

GET http://localhost:3000

###

GET http://localhost:3000/post?sender=123457

###

GET http://localhost:3000/post/635f918dc1380bbbfbfdd469

###
POST http://localhost:3000/post
Content-Type: application/json

{
    "message" : "this is my new message",
    "sender" : "123457"
}
