###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=123456
#/post?sender=<sender id>

###

GET http://localhost:3000/post/63777da308fe460adee2aecf
#/post/<id of the post>

###
POST http://localhost:3000/post
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOGNhZWRlMDczOTU3NWQ0NDEzMzE4NCIsImlhdCI6MTY3MDE2NDE5NywiZXhwIjoxNjcwMTY3Nzk3fQ.w4OWLLxiYPqdry22BnnZeuuOxy17bjgulwO6ZbRsdpM
Content-Type: application/json

{
    "message" : "this is my new message",
    "sender" : "123456"
}
###

PUT http://localhost:3000/post/637783d52ec6cd8191c31a0f
Content-Type: application/json

{
    "message" : "This is a updated psot",
    "sender" : "12345"
}
###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"12345"
}

###
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"user1@gmail.com",
    "password":"12345"
}

###